### ISSUE TITLE
Any plans for the upcoming colourspaces: display-p3, rec2020?

### ISSUE THREAD

**Issue by dgrammatiko** [thednp/color#1]
Ref:  
- css color(): https://caniuse.com/css-color-function
- webkit: https://webkit.org/blog/10042/wide-gamut-color-in-css-with-display-p3/
- hwb: https://caniuse.com/mdn-css_types_color_hwb
- lch: https://caniuse.com/mdn-css_types_color_hwb
- lab: https://caniuse.com/css-lch-lab

**Comment by thednp** [comment]
Sup @dgrammatiko:
* hwb is already implemented and [documented](https://github.com/thednp/color/wiki/Color-Wiki#tohwb)
* `color()`, `lch()` and `lab()` are still under work and I haven't found some code samples to play with, yet.

What's your take on it?

**Comment by dgrammatiko** [comment]
I'm using an alternative lib: [colorjs.io](https://colorjs.io) for my pickers so I can roll things with display-P3 (by the end of the year all browsers will support display-p3,lch,lab,etc it's on the interop 2022: https://web.dev/interop-2022/). The problem with the wider gamut is that it might need some out of bounds clipping and this might get too complicated too soon. Anyways this looks great and I'm sure you will support all the new fancy staff later on. Keep up the good work!

**Comment by thednp** [comment]
Thanks!

My main focus atm is to have it all TypeScript setup (sources and testing suite) and easy to integrate with existing tech (forms, compilers, today's browsers, etc). In the future we'll do what's in the future.

Thanks again!
